# Generated by Django 5.2 on 2025-04-19 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_donationclaim'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='donationclaim',
            unique_together=set(),
        ),
    ]
