# Generated by Django 5.2 on 2025-05-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_donationclaim_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='warning_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
