# Generated by Django 5.2.3 on 2025-06-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_warning_delete_donorwarning'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('natural_disaster', 'Natural Disaster'), ('weather_alert', 'Weather Alert'), ('health_crisis', 'Health Crisis'), ('security_alert', 'Security Alert'), ('system_alert', 'System Alert'), ('admin_alert', 'Admin Alert')], default='admin_alert', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('location', models.JSONField(blank=True, default=dict)),
                ('affected_areas', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_generated', models.BooleanField(default=False)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
